apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: aiops
spec:
  ports:
    - port: 9093
      targetPort: 9093
      name: api
  selector:
    app: alertmanager
  type: ClusterIP
