package com.aiops.notification.dto;

import com.aiops.notification.entity.NotificationStatus;
import lombok.*;

import java.time.LocalDateTime;

/**
 * ==============================================================
 * NotificationResponseDTO
 * ==============================================================
 *
 * PURPOSE
 * -------
 * Represents the data returned to the client.
 *
 * Unlike the Request DTO, this contains additional
 * fields generated by the server such as:
 *
 * ✔ id
 * ✔ status
 * ✔ createdAt
 *
 * This ensures the client knows exactly what
 * was stored in the database.
 */

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class NotificationResponseDTO {

    /**
     * Database generated ID.
     */
    private Long id;

    /**
     * Recipient email.
     */
    private String recipient;

    /**
     * Notification subject.
     */
    private String subject;

    /**
     * Notification message.
     */
    private String message;

    /**
     * Current notification status.
     */
    private NotificationStatus status;

    /**
     * Timestamp when the notification
     * was created.
     */
    private LocalDateTime createdAt;

}