apiVersion: v1
kind: Service
metadata:
  name: transaction-service
  namespace: aiops
spec:
  ports:
    - port: 8081
      targetPort: 8081
      name: http
  selector:
    app: transaction-service
  type: ClusterIP
