server:
  port: 8081

spring:
  application:
    name: transaction-service

  datasource:
    url: jdbc:postgresql://postgres:5432/aiops_db
    username: aiops_user
    password: aiops_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
