apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: aiops
spec:
  ports:
    - port: 8083
      targetPort: 8083
      name: http
  selector:
    app: notification-service
  type: ClusterIP
