{
 "title": "HTTP Metrics",
 "tags": [
  "aiops",
  "http"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "application", "label": "Application", "query": "label_values(up, job)" }
  ]
 },
 "panels": [
  {
   "title": "HTTP Requests Rate (req/sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{job=\"$application\"}[5m]))",
     "legendFormat": "Total Requests Rate"
    }
   ]
  },
  {
   "title": "Error Rate (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(rate(http_server_requests_seconds_count{status=~\"5.*\",job=\"$application\"}[5m])) / sum(rate(http_server_requests_seconds_count{job=\"$application\"}[5m]))) * 100 or vector(0)",
     "legendFormat": "HTTP 5xx Error Rate"
    }
   ]
  },
  {
   "title": "HTTP 2xx Success Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{status=~\"2.*\",job=\"$application\"}[5m]))",
     "legendFormat": "2xx Successes"
    }
   ]
  },
  {
   "title": "HTTP 4xx Client Errors",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{status=~\"4.*\",job=\"$application\"}[5m]))",
     "legendFormat": "4xx Client Errors"
    }
   ]
  },
  {
   "title": "HTTP 5xx Server Errors",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{status=~\"5.*\",job=\"$application\"}[5m]))",
     "legendFormat": "5xx Server Errors"
    }
   ]
  }
 ]
}