package com.aiops.transaction.dto;

import com.aiops.transaction.entity.TransactionStatus;
import jakarta.validation.constraints.DecimalMin;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.*;

import java.math.BigDecimal;

/**
 * ==============================================================
 * TransactionRequestDTO
 * ==============================================================
 *
 * PURPOSE
 * -------
 * This DTO represents the data sent by the client
 * when creating or updating a transaction.
 *
 * Why not use the Entity directly?
 * --------------------------------
 * The Entity represents our database table.
 *
 * The client should NEVER decide values like:
 * - id
 * - createdAt
 * - updatedAt
 *
 * Those are generated by our application.
 */

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class TransactionRequestDTO {

    /**
     * Transaction amount.
     *
     * @DecimalMin ensures the amount is greater than 0.
     */
    @NotNull(message = "Amount is required")
    @DecimalMin(value = "0.01", message = "Amount must be greater than zero")
    private BigDecimal amount;

    /**
     * Transaction status.
     */
    @NotNull(message = "Status is required")
    private TransactionStatus status;

    /**
     * Description of the transaction.
     */
    @NotBlank(message = "Description cannot be empty")
    private String description;

}