apiVersion: v1
kind: Service
metadata:
  name: k8s-observer-service
  namespace: aiops
spec:
  ports:
    - port: 8084
      targetPort: 8084
      name: http
  selector:
    app: k8s-observer-service
  type: ClusterIP
