apiVersion: v1
kind: Secret
metadata:
  name: gemini-secret
  namespace: aiops
type: Opaque
data:
  # Base64 encoded placeholder ("mock-key")
  # Replace with base64 encoded value of your real Gemini API key
  gemini-api-key: QVEuQWI4Uk42THI4cmllaTNZY0xXZ1p2NEJFUUNpRW5LLW8xWE9rWll0dUtwSEVUeHdlRlE=
