server:
  port: 8084

spring:
  application:
    name: k8s-observer-service

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

healing:
  service:
    url: http://healing-service:8082
